Repository railslink/railslink, pull requests merged in 2019-10, with the labels that each got.

#107 upgrade ruby from 2.4.4 to 2.5.7
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  spec/fixtures/vcr/IpInfo/private_ip_ranges/is_unsuccessful.yml
  spec/fixtures/vcr/IpInfo/private_ip_ranges/sets_a_message_about_why.yml
Labels: dependencies, devops

#108 Upgrade circleci postgres
  .circleci/config.yml
Labels: devops

#111 Ensure Restart with Existing PID
  Dockerfile
Labels: devops, enhancement

#112 Update loofah gem to fix vulnerability
  Gemfile.lock
Labels: dependencies
